### PR TITLE
test(cli): add regression test for nested subdir gitignore mutation

### LINKED ISSUE #48: KAL-PAT003 が循環依存のない Python/Rust モジュール間で偽陽性を報告する
## 概要

`kalos check` の最新ビルド（commit `d87e41b`）で複数リポジトリを評価したところ、実際には循環依存が存在しない Python / Rust モジュール間で `KAL-PAT003` (Circular dependency detected) が error として報告される。

### 事例 1: Python 標準ライブラリしか使わないファイル間で循環を誤報告（agentic-core / DoctoralResearch）

\`\`\`bash
kalos check --format human /path/to/agentic-core
\`\`\`

出力:
\`\`\`
.agents/skills/skill-creator/eval-viewer/generate_review.py:1  error[KAL-PAT003]
  Circular dependency detected among modules:
  .agents/skills/skill-creator/eval-viewer/generate_review.py ->
  .agents/skills/skill-creator/scripts/generate_report.py
\`\`\`

しかし、両ファイルの import は標準ライブラリのみで、互いを参照していない:

\`\`\`bash
$ grep -E '^(from|import)' .agents/skills/skill-creator/eval-viewer/generate_review.py
import argparse
import base64
import json
import mimetypes
import os
import re
import signal
import subprocess
import sys
import time
import webbrowser
from functools import partial
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path

$ grep -E '^(from|import)' .agents/skills/skill-creator/scripts/generate_report.py
import argparse
import html
import json
import sys
from pathlib import Path
\`\`\`

相互参照ゼロ。

### 事例 2: tests → src の一方向依存を循環と誤報告（agentic-memory）

出力:
\`\`\`
src/agentic_memory/cli.py:1  error[KAL-PAT003]
  Circular dependency detected among modules:
  src/agentic_memory/cli.py -> src/agentic_memory/core/cleanup.py -> src/agentic_memory/core/evidence.py ->
  src/agentic_memory/core/health.py -> src/agentic_memory/core/index.py -> src/agentic_memory/core/query.py ->
  src/agentic_memory/core/scorer.py -> src/agentic_memory/core/search.py -> src/agentic_memory/core/signals.py ->
  src/agentic_memory/core/state.py -> src/agentic_memory/core/stats.py -> src/agentic_memory/core/tokenizer.py ->
  src/agentic_memory/server.py -> tests/test_state.py
\`\`\`

14 モジュールを跨ぐ経路が循環として報告されるが、\`src/\` から \`tests/\` への import は存在しない:

\`\`\`bash
$ grep -rE '^(from|import)\s+tests' src/
# (ゼロ件)
\`\`\`

\`tests/test_state.py\` は \`from agentic_memory.core import index, note, state\` のみで、tests → src の一方向 import（Python 標準パターン）。

同じ検出は \`tests/test_search.py -> tests/test_server.py\` にも見られるが、test 間の相互 import も存在しない。

### 事例 3 (要追加検証): Rust facade パターンを循環と誤報告（ferritex）

\`\`\`
crates/ferritex-core/src/font/api.rs:1  error[KAL-PAT003]
  font/api.rs -> font/opentype.rs

crates/ferritex-core/src/graphics/api.rs:1  error[KAL-PAT003]
  graphics/api.rs -> graphics/tikz.rs -> parser/api.rs -> parser/package_loading.rs

crates/ferritex-core/src/typesetting/api.rs:1  error[KAL-PAT003]
  typesetting/api.rs -> typesetting/knuth_plass.rs -> typesetting/line_breaker.rs -> typesetting/math_layout.rs

crates/ferritex-cli/src/lsp_server.rs:1  error[KAL-PAT003]
  lsp_server.rs -> main.rs -> watch_runner.rs
\`\`\`

4 件すべて \`xxx/api.rs -> 周辺モジュール\` または \`親モジュール -> 子モジュール\` のパターンで、Rust の facade 構成（\`mod foo; pub use foo::*;\`）を循環と誤判定している疑いがある（実コードでの双方向 \`mod\` 宣言は未確認、要追加検証）。

## 期待される動作

以下のケースを KAL-PAT003 として検出しない:

1. tests → src の一方向 import（src → tests が存在しない場合）
2. 親モジュール → 子モジュールの facade パターン（子 → 親が存在しない場合）
3. 相互参照のない同一ディレクトリ内ファイル間の誤関連付け

## 推定原因

- 循環検出ロジックが strongly connected component (SCC) ではなく、reachability を使っている可能性
- もしくは CodeQL クエリが \`from pkg.mod import X\` や \`mod xxx; pub use xxx::*;\` を双方向エッジとしてグラフに追加している可能性

## 影響

- Python 3 リポジトリ（agentic-core / agentic-memory / DoctoralResearch）で合計 5 件の偽陽性 error
- ferritex で 4 件（要追加検証）
- overall スコアが 100 → 93-97 に不当に減点される
- ユーザーが実在しない循環依存の修正に時間を取られる

## 補足

- 本問題は \`kalos 0.1.0\` build commit \`d87e41b\` (2026-04-10) で再現
- issue #39 で修正された「kalos 自身の \`src/domains/metrics\` 内循環依存」は真の循環であり、本 issue とは別問題
- 評価ログは \`tmp/kalos-eval-2026-04-10-rebuild/\` に保存済み

### PR DESCRIPTION
**Pull request by RK0429**
Closes #48

### CODE REVIEW

**Comment by RK0429** [comment]
Automated merge prep failed: rebase onto origin/develop produced semantic conflicts across src/adapters/tool_cache/managed_bundle.rs and src/domains/diagnostics/mod.rs. The branch contains 6 commits with substantial overlap against already-merged develop PRs (#71, #72, #74, #76, #85), so confidence in a clean semantic resolution was too low. Manual review required.
